In [3]:
import numpy as np

In [4]:
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

In [5]:
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [8]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1 * x2

result

CPU times: total: 15.6 ms
Wall time: 165 ms


833332333333500000

In [9]:
%%time
result = np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 1.51 ms


In [1]:
import urllib.request

urllib.request.urlretrieve("https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv", "climate.txt")

('climate.txt', <http.client.HTTPMessage at 0x272c92d1e90>)

In [6]:
weight = np.array([0.3, 0.2, 0.5])

In [7]:
climate_data = np.genfromtxt('climate.txt', delimiter=',' , skip_header=1)

In [8]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [10]:
climate_data.shape

(10000, 3)

In [11]:
yields = climate_data @ weight

In [17]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [18]:
yields.shape

(10000,)

In [19]:
yields.reshape(10000, 1)

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [20]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [24]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [25]:
climate_result = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [26]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [28]:
np.savetxt('climate_result.txt', 
           climate_result,
           delimiter=',',
           fmt='%.2f',
           header='temperature,rainfall,humidity,yield_apples',
           comments='')

In [29]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [30]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [31]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [32]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [33]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [34]:
(arr1 == arr2).sum()

np.int64(3)

In [35]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [36]:
arr3.shape

(3, 2, 4)

In [37]:
arr3[1, 1, 2]

np.float64(36.0)

In [38]:
arr3[1:, 0:1, 0:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [39]:
arr3[1:, 1, 3]

array([18., 43.])

In [41]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones([3, 3, 3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
np.eye(1)

array([[1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.random.rand(2, 3)

array([[0.26837635, 0.33359316, 0.31426058],
       [0.99302548, 0.9757907 , 0.17230909]])

In [46]:
np.full((2, 3), 45)

array([[45, 45, 45],
       [45, 45, 45]])

In [47]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [48]:
np.linspace(2, 23, 3)

array([ 2. , 12.5, 23. ])

In [49]:
np.__version__

'2.0.0'

In [51]:
zero_vector = np.zeros(10)

In [52]:
memory_size = zero_vector.nbytes

In [53]:
memory_size

80

In [54]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [56]:
null_vector = np.zeros(10)

In [57]:
null_vector[4] = 1

In [58]:
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [60]:
vet1 = np.arange(10, 50)

In [65]:
vet1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [66]:
vet2 = np.arange(9).reshape(3, 3)

In [67]:
vet2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
vet3 = np.array([1,2,0,0,4,0] )

In [70]:
np.nonzero(vet3)[0]

array([0, 1, 4])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.random.rand(3, 3, 3)

array([[[0.0931394 , 0.63693389, 0.65026262],
        [0.90619407, 0.52643638, 0.37886577],
        [0.2577745 , 0.6316079 , 0.58269339]],

       [[0.81740113, 0.86269789, 0.58273861],
        [0.74655572, 0.34916401, 0.9127493 ],
        [0.86555525, 0.05136191, 0.91723525]],

       [[0.66761904, 0.58262557, 0.03066209],
        [0.78841725, 0.32643653, 0.56214553],
        [0.35666247, 0.09611623, 0.53695173]]])

In [73]:
vet5 = np.random.rand(10, 10)

In [74]:
vet5.max()

np.float64(0.9988042735884629)

In [75]:
vet5.min()

np.float64(0.009193992450807653)

In [76]:
vet6 = np.random.rand(30)

In [77]:
vet6.mean()

np.float64(0.4868967887174273)

In [96]:
vet7 = np.zeros((5, 5))

In [97]:
vet7

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [101]:
vet7[0, :] = 1 # top row
vet7[:, 0] = 1 # left column
vet7[: , -1] = 1 # right column
vet7[4, :] = 1 # bottom row

In [102]:
vet7

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [103]:
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

In [104]:
row, col = existing_array.shape

In [105]:
new_array = np.zeros((row + 2, col + 2))

In [106]:
new_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [107]:
new_array[1:-1, 1:-1] = existing_array

In [108]:
new_array

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 0.],
       [0., 4., 5., 6., 0.],
       [0., 7., 8., 9., 0.],
       [0., 0., 0., 0., 0.]])

In [109]:
values = np.array([1,2,3,4])

In [133]:
np.diag(values, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [137]:
vet8 = np.zeros((8, 8))

In [138]:
vet8

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [140]:
vet8[::2, 1::2] = 1

In [141]:
vet8

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [142]:
vet8[1::2, ::2] = 1

In [143]:
vet8

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [144]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)

In [145]:
index

(np.int64(1), np.int64(5), np.int64(4))